name: DevPipeline
env:
  AZURE_WEBAPP_NAME: eusqaenvwebapp
  AZURE_WEBAPP_NAME_PROD: eusprodenvwebapp
  AZURE_WEBAPP_PACKAGE_PATH: .
  DOTNET_VERSION: '6'
'on':
  #push:
  #  branches:
  #    - test
  #pull_request:
  #  branches:
  #    - test
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3 
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}" 
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: publish
        run: 'dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: '${{env.DOTNET_ROOT}}/myapp/**'
  QA-Deployment:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: qa
      url: '${{ steps.deploy-to-webapp.outputs.webapp-url }}'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: published-app
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.AZURE_WEBAPP_NAME }}'
          publish-profile: '${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}'
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
  
  Prod-Deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: QA-Deployment
    environment:
      name: prod
      url: '${{ steps.deploy-to-webapp.outputs.webapp-url }}'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: published-app
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.AZURE_WEBAPP_NAME_PROD }}'
          publish-profile: '${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}'
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
